name: Release Build

on:
  release:
    types: [published]

permissions: write-all

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - uses: egor-tensin/vs-shell@v2
      with:
        arch: x86

    - name: Run build script
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\build-windows.bat

    - name: Create zip
      run: 7z a dist-windows.zip dist-windows

    - uses: AButler/upload-release-assets@v2.0
      with:
        files: 'dist-windows.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
