name: Release Build

on:
  release:
    types: [published]

permissions: write-all

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - uses: egor-tensin/vs-shell@v2
      with:
        arch: x86

    - name: Run build script
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\build-windows.bat

    - name: Create zip
      run: 7z a dist-windows.zip dist-windows

    - name: Find release upload URL
      run: |
         $response = Invoke-RestMethod https://api.github.com/repos/actions/checkout/releases/latest
         $upload_url = $response.upload_url
         echo "UPLOAD_URL=$upload_url" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Attach Windows build to release
      uses: actions/upload-release-asset@v1
      id: upload-release-asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: dist-windows.zip
        asset_name: dist-windows.zip
        asset_content_type: application/zip
