name: Release Build

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - uses: egor-tensin/vs-shell@v2
      with:
        arch: x86

    - name: Run build script
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\build-windows.bat

    - name: Create zip
      run: 7z a dist-windows.zip dist-windows

    - name: Find release upload URL
      run: |
         Invoke-RestMethod https://api.github.com/repos/actions/checkout/releases/latest
         echo UPLOAD_URL=$response.upload_url >> $GITHUB_ENV
      shell: pwsh

    - name: Attach Windows build to release
      uses: actions/upload-release-asset@v1
      id: upload-release-asset
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: dist-windows.zip
        asset_name: dist-windows.zip
        asset_content_type: application/zip
